<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="EPUAKHAW5257" name="SearchTests" tests="4" failures="2" timestamp="06 Feb 2018 15:37:12 GMT" time="48.318" errors="0">
  <testcase name="searchWithCorrectData" time="9.061" classname="SearchTests"/>
  <testcase name="searchByProductCategory" time="15.259" classname="SearchTests">
    <failure type="com.codeborne.selenide.ex.ElementNotFound" message="Element not found {By.className: //li[@class=&#039;item&#039;]}
Expected: visible">
      <![CDATA[Element not found {By.className: //li[@class='item']}Expected: visibleScreenshot: file:/D:/gitHabRepo/sashabaliuk/selenide/build/reports/tests/1517931409180.0.pngPage source: file:/D:/gitHabRepo/sashabaliuk/selenide/build/reports/tests/1517931409180.0.htmlTimeout: 4 s.Caused by: java.lang.IndexOutOfBoundsException: Index: 2, Size: 0at com.codeborne.selenide.impl.CollectionElement.createElementNotFoundError(CollectionElement.java:52)at com.codeborne.selenide.impl.WebElementSource.checkCondition(WebElementSource.java:59)at com.codeborne.selenide.commands.Should.should(Should.java:35)at com.codeborne.selenide.commands.Should.execute(Should.java:29)at com.codeborne.selenide.commands.Should.execute(Should.java:12)at com.codeborne.selenide.commands.Commands.execute(Commands.java:144)at com.codeborne.selenide.impl.SelenideElementProxy.dispatchAndRetry(SelenideElementProxy.java:87)at com.codeborne.selenide.impl.SelenideElementProxy.invoke(SelenideElementProxy.java:63)at com.sun.proxy.$Proxy5.shouldHave(Unknown Source)at SearchTests.searchByProductCategory(SearchTests.java:39)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:373)at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:334)at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:119)at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:407)Caused by: java.lang.IndexOutOfBoundsException: Index: 2, Size: 0at java.util.ArrayList.rangeCheck(ArrayList.java:657)at java.util.ArrayList.get(ArrayList.java:433)at com.codeborne.selenide.impl.CollectionElement.getWebElement(CollectionElement.java:40)at com.codeborne.selenide.impl.WebElementSource.checkCondition(WebElementSource.java:44)... 37 more]]>
    </failure>
  </testcase> <!-- searchByProductCategory -->
  <testcase name="searchWithIncorrectData" time="5.468" classname="SearchTests"/>
  <testcase name="searchByProductCategoryWithAdditionalParameters" time="18.530" classname="SearchTests">
    <failure type="com.codeborne.selenide.ex.ElementNotFound" message="Element not found {By.className: //li[@class=&#039;item&#039;]}
Expected: visible">
      <![CDATA[Element not found {By.className: //li[@class='item']}Expected: visibleScreenshot: file:/D:/gitHabRepo/sashabaliuk/selenide/build/reports/tests/1517931425739.1.pngPage source: file:/D:/gitHabRepo/sashabaliuk/selenide/build/reports/tests/1517931425739.1.htmlTimeout: 4 s.Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0at com.codeborne.selenide.impl.CollectionElement.createElementNotFoundError(CollectionElement.java:52)at com.codeborne.selenide.impl.WebElementSource.checkCondition(WebElementSource.java:59)at com.codeborne.selenide.commands.Should.should(Should.java:35)at com.codeborne.selenide.commands.Should.execute(Should.java:29)at com.codeborne.selenide.commands.Should.execute(Should.java:12)at com.codeborne.selenide.commands.Commands.execute(Commands.java:144)at com.codeborne.selenide.impl.SelenideElementProxy.dispatchAndRetry(SelenideElementProxy.java:87)at com.codeborne.selenide.impl.SelenideElementProxy.invoke(SelenideElementProxy.java:63)at com.sun.proxy.$Proxy5.shouldHave(Unknown Source)at SearchTests.searchByProductCategoryWithAdditionalParameters(SearchTests.java:48)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:373)at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:334)at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:119)at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:407)Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0at java.util.ArrayList.rangeCheck(ArrayList.java:657)at java.util.ArrayList.get(ArrayList.java:433)at com.codeborne.selenide.impl.CollectionElement.getWebElement(CollectionElement.java:40)at com.codeborne.selenide.impl.WebElementSource.checkCondition(WebElementSource.java:44)... 37 more]]>
    </failure>
  </testcase> <!-- searchByProductCategoryWithAdditionalParameters -->
</testsuite> <!-- SearchTests -->
